title: MLP Docs
description: A fast ML inference server written in Python
theme: just-the-docs

url: https://ekanshagrawal.com/mlp

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
